version: "3"
services:
  envoy-proxy:
    build:
      context: ./
      dockerfile: ./Dockerfile.local
    image: olamai/envoy-proxy-local:0.0.1
    expose:
      - "9091"
    ports:
      - "9091:9091"
