version: "3"
services:
  envoy-proxy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: olamai/envoy-proxy:0.0.1
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
